// English -> kana reading rules (replicated from AqKanji2Koe behavior).

export const LETTER_NAME = {
  A: 'エー', B: 'ビー', C: 'シー', D: 'ディー', E: 'イー', F: 'エフ',
  G: 'ジー', H: 'エイチ', I: 'アイ', J: 'ジェー', K: 'ケー', L: 'エル',
  M: 'エム', N: 'エヌ', O: 'オー', P: 'ピー', Q: 'キュー', R: 'アール',
  S: 'エス', T: 'ティー', U: 'ユー', V: 'ブイ', W: 'ダブリュー',
  X: 'エックス', Y: 'ワイ', Z: 'ゼット',
};

export const WORD_TABLE = new Map(Object.entries({
  'ability': 'アビリティー',
  'about': 'アバウット',
  'above': 'アボブ',
  'acceleration': 'アクセレラション',
  'accent': 'アクセント',
  'accept': 'アクセプト',
  'account': 'アカウント',
  'accountant': 'アッカウンタント',
  'across': 'アクロス',
  'action': 'アクション',
  'actor': 'アクター',
  'advanced': 'アドバンスド',
  'advantage': 'アドバンテージ',
  'advisor': 'アドバイザー',
  'after': 'アフター',
  'afternoon': 'アフタヌーン',
  'again': 'アゲーン',
  'agree': 'アグリー',
  'air': 'エア',
  'airplane': 'エアープラン',
  'airport': 'エアーポート',
  'algorithm': 'アルゴリズム',
  'allowance': 'アローアンス',
  'along': 'アロング',
  'alpha': 'アルファ',
  'alphabet': 'アルファベット',
  'also': 'アルソ',
  'always': 'アルウェース',
  'amazon': 'アマゾン',
  'amount': 'アマウント',
  'an': 'エーエヌ',
  'analysis': 'アナリシス',
  'analyst': 'アナリスト',
  'ancient': 'アンシーント',
  'and': 'アンド',
  'android': 'アンドロイド',
  'angeles': 'アンゲレス',
  'animal': 'アニマル',
  'anniversary': 'アニバーサリー',
  'another': 'アナター',
  'answer': 'アンスワー',
  'antibody': 'アンティボディー',
  'aperture': 'アパーチャ',
  'apparatus': 'アッパラチュス',
  'apple': 'アップル',
  'application': 'アプリケーション',
  'appointment': 'アポイントメント',
  'approach': 'アプローチ',
  'aquarium': 'アクアリウム',
  'arch': 'アーチ',
  'architect': 'アーキテクト',
  'arena': 'アリーナ',
  'argue': 'アーグ',
  'arm': 'アーム',
  'around': 'アラウンド',
  'arrangement': 'アレンジメント',
  'article': 'アーティクル',
  'artificial': 'アーティフィシャル',
  'artist': 'アーティスト',
  'ask': 'アスク',
  'assembly': 'アセンブリー',
  'assist': 'アシスト',
  'assumption': 'アシュヌプション',
  'at': 'エーティー',
  'athlete': 'アスリート',
  'attack': 'アタック',
  'attention': 'アテンション',
  'attitude': 'アッティチュード',
  'audience': 'オーディエンス',
  'audio': 'オーディオ',
  'author': 'オーター',
  'auto': 'オート',
  'automation': 'オートヌション',
  'autumn': 'オータム',
  'average': 'アベレージ',
  'award': 'オーアード',
  'away': 'オーエー',
  'bachelor': 'バチェラー',
  'back': 'バック',
  'backward': 'バックワード',
  'bacteria': 'バクテリア',
  'bake': 'バケ',
  'ball': 'バル',
  'banana': 'バナナ',
  'bank': 'バンク',
  'basic': 'ベーシック',
  'bathroom': 'バスルーム',
  'battery': 'バッテリー',
  'beach': 'ビーチ',
  'bear': 'ビアー',
  'beat': 'ビート',
  'beauty': 'ビューティー',
  'because': 'ベコース',
  'bedroom': 'ベッドルーム',
  'beer': 'ビール',
  'before': 'ベフォアー',
  'begin': 'ベジン',
  'beginner': 'ビギナー',
  'beginning': 'ベジニング',
  'behavior': 'ビヘイビア',
  'behind': 'ビハインド',
  'belong': 'ベロング',
  'below': 'ベロー',
  'benefit': 'ベネフィット',
  'berry': 'ベリー',
  'beside': 'ベシード',
  'best': 'ベスト',
  'better': 'ベター',
  'between': 'ベトウィーン',
  'bike': 'バイク',
  'bill': 'ビル',
  'billion': 'ビリオン',
  'bird': 'バード',
  'birth': 'バース',
  'birthday': 'バースデイ',
  'black': 'ブラック',
  'blew': 'ブレウ',
  'blue': 'ブルー',
  'boat': 'ボート',
  'body': 'ボディー',
  'boil': 'ボイル',
  'bond': 'ボンド',
  'book': 'ブック',
  'boss': 'ボス',
  'both': 'ボス',
  'bottle': 'ボトル',
  'bottom': 'ボトム',
  'bought': 'ボフット',
  'bounce': 'バウンド',
  'boxer': 'ボクサー',
  'boy': 'ボーイ',
  'bread': 'ブレッド',
  'breakfast': 'ブリークファスト',
  'brew': 'ブリュー',
  'bring': 'ブリング',
  'bronze': 'ブロンズ',
  'brother': 'ブラザー',
  'brown': 'ブラウン',
  'browser': 'ブラウザ',
  'brush': 'ブラシ',
  'budget': 'バジェット',
  'build': 'ビルド',
  'built': 'ビルト',
  'business': 'ビジネス',
  'busy': 'ビジー',
  'butter': 'バター',
  'byte': 'バイト',
  'cab': 'キャブ',
  'cad': 'キャド',
  'cafe': 'カフェ',
  'cake': 'ケーキ',
  'calendar': 'カレンダ',
  'call': 'シーエーエルエル',
  'called': 'カレド',
  'calorie': 'カロリー',
  'came': 'カム',
  'camera': 'カメラ',
  'can': 'カン',
  'canon': 'キャノン',
  'capsule': 'カプセル',
  'captain': 'キャプテン',
  'car': 'カー',
  'carbohydrate': 'カーボヒドラット',
  'card': 'カルト',
  'careful': 'カレフル',
  'carry': 'キャリー',
  'case': 'ケース',
  'cash': 'キャッシュ',
  'cat': 'キャット',
  'catch': 'キャッチ',
  'caught': 'カフット',
  'cause': 'コース',
  'celebration': 'セレブラション',
  'cell': 'セル',
  'center': 'センター',
  'century': 'センチュリー',
  'certificate': 'サティフィケット',
  'champagne': 'シャンパン',
  'champion': 'チャンピオン',
  'championship': 'チャンピオンシップ',
  'change': 'チェンジ',
  'channel': 'チャネル',
  'chapter': 'チャプター',
  'charge': 'チャージ',
  'chart': 'チャート',
  'cheap': 'キープ',
  'check': 'チェック',
  'cheese': 'キース',
  'cherry': 'チェリー',
  'chest': 'チェスト',
  'child': 'チャイルド',
  'china': 'チャイナ',
  'choice': 'コイス',
  'choose': 'クース',
  'christmas': 'クリスマス',
  'chrome': 'クロヌ',
  'church': 'チャーチ',
  'city': 'シティ',
  'claim': 'クレーム',
  'class': 'クラス',
  'clean': 'クリーン',
  'clear': 'クリア',
  'client': 'クライアント',
  'climate': 'クリヌット',
  'clinic': 'クリニック',
  'clock': 'クロック',
  'close': 'クローズ',
  'cloud': 'クラウド',
  'coach': 'コーチ',
  'cocktail': 'カクテル',
  'code': 'コード',
  'coding': 'コディング',
  'coffee': 'コフィー',
  'cognitive': 'コグニティブ',
  'cold': 'コルド',
  'college': 'カレッジ',
  'color': 'カラー',
  'come': 'コム',
  'command': 'コマンド',
  'commerce': 'コマース',
  'common': 'コモン',
  'company': 'カンパニー',
  'compass': 'コンパス',
  'competition': 'コンペティション',
  'complete': 'コンプレット',
  'composition': 'コンポシション',
  'computer': 'コムプター',
  'computing': 'コヌプティング',
  'concept': 'コンセプト',
  'conclusion': 'コンクルション',
  'conference': 'カンファレンス',
  'constant': 'コンスタント',
  'consultant': 'コンシュルタント',
  'consumer': 'コンシュヌー',
  'continent': 'コンティネント',
  'continue': 'コンティヌ',
  'control': 'コントロル',
  'convenience': 'コンブニーンス',
  'cook': 'クック',
  'cool': 'クール',
  'copper': 'コッパー',
  'copy': 'コピー',
  'corner': 'コーナー',
  'cost': 'コスト',
  'could': 'カウルド',
  'counseling': 'カウンセリング',
  'count': 'カウント',
  'country': 'カントリー',
  'coupon': 'クーポン',
  'course': 'カアース',
  'court': 'カアート',
  'cover': 'カバー',
  'cream': 'クリーム',
  'create': 'クリエート',
  'credit': 'クレジット',
  'crew': 'クルー',
  'crowd': 'クロード',
  'crown': 'クラウン',
  'cup': 'カップ',
  'currency': 'カレンシー',
  'current': 'カレント',
  'curry': 'カレー',
  'customer': 'クストマー',
  'cut': 'カット',
  'cycle': 'サイクル',
  'cyclist': 'サイクリスト',
  'damage': 'ダムッジ',
  'dance': 'ダンス',
  'danger': 'ダンガー',
  'dark': 'ダーク',
  'data': 'データ',
  'database': 'データベース',
  'date': 'デイト',
  'daughter': 'ダフター',
  'day': 'デイ',
  'dead': 'デッド',
  'deadline': 'デッドライン',
  'dear': 'ディアー',
  'death': 'デス',
  'debate': 'ディベート',
  'debit': 'デビット',
  'debt': 'デブト',
  'decade': 'デカード',
  'decide': 'デシード',
  'decision': 'デシジョン',
  'deep': 'ディープ',
  'deer': 'ディアー',
  'defender': 'ディフェンダー',
  'defense': 'ディフェンス',
  'degree': 'デグリー',
  'dentist': 'デンティスト',
  'department': 'デパートメント',
  'deposit': 'デポジット',
  'depth': 'デプス',
  'desert': 'デザート',
  'design': 'デザイン',
  'designer': 'デザイナー',
  'desk': 'デスク',
  'developer': 'ディベロッパー',
  'development': 'デベロップメント',
  'device': 'デバイス',
  'diagnosis': 'ディアグヌシス',
  'diagram': 'ダイアグラム',
  'diet': 'ディート',
  'different': 'ディフェレント',
  'dinner': 'ディナー',
  'diploma': 'ディプロマ',
  'direction': 'ダイアクション',
  'director': 'ディレクター',
  'dirt': 'ダート',
  'dirty': 'ダーティー',
  'disadvantage': 'ディサドバンタッジ',
  'disagree': 'ディサグリー',
  'discount': 'ディスカウント',
  'discover': 'ディスカバー',
  'discuss': 'ディスクス',
  'disease': 'ディシース',
  'dish': 'ディシュ',
  'divide': 'ディビード',
  'division': 'ディビション',
  'do': 'ドゥー',
  'doctor': 'ドクター',
  'dog': 'ドッグ',
  'dollar': 'ドル',
  'dolphin': 'ドルフィン',
  'done': 'ドン',
  'door': 'ドア',
  'dot': 'ドット',
  'double': 'ダウブル',
  'doubt': 'ダウト',
  'down': 'ダウン',
  'dream': 'ドリーム',
  'dress': 'ドレス',
  'drink': 'ドリンク',
  'drive': 'ドライブ',
  'drop': 'ドロップ',
  'dry': 'ドライ',
  'duck': 'ダック',
  'during': 'デュリング',
  'dust': 'デュスト',
  'dvd': 'ディブイディ',
  'each': 'イーチ',
  'early': 'イアーリー',
  'earth': 'アース',
  'east': 'イースト',
  'easy': 'イージー',
  'economist': 'エコノミスト',
  'economy': 'エコノミイ',
  'edge': 'エッジ',
  'editor': 'エディター',
  'education': 'エデュカション',
  'effect': 'エフェクト',
  'eight': 'イーイット',
  'eighth': 'イーイス',
  'either': 'アイター',
  'electric': 'エレクトリック',
  'electrical': 'エレクトリカル',
  'elementary': 'エレメンタリー',
  'elephant': 'エレファント',
  'else': 'エルス',
  'email': 'エヌール',
  'emotion': 'エヌーション',
  'emotional': 'エモーショナル',
  'employee': 'エヌプロイーエ',
  'enemy': 'エネミイ',
  'energy': 'エヌージー',
  'engine': 'エンジン',
  'engineer': 'エンジニアー',
  'english': 'イングリッシュ',
  'enjoy': 'エンジョイー',
  'enormous': 'エヌーヌウス',
  'enough': 'エヌフ',
  'enter': 'エンター',
  'entire': 'エンタイア',
  'environment': 'エンビロンメント',
  'equal': 'イコール',
  'equation': 'エクアション',
  'equipment': 'イクイップメント',
  'error': 'エラー',
  'escape': 'エスカペ',
  'especially': 'エスペシアリー',
  'estimate': 'エスティメット',
  'europe': 'ヨーロッパ',
  'even': 'イーブン',
  'evening': 'イブニング',
  'event': 'イベント',
  'ever': 'エバー',
  'every': 'エブリー',
  'evidence': 'エビデンス',
  'example': 'エクサンプル',
  'excel': 'エクセル',
  'exchange': 'エクスチェンジ',
  'excited': 'エクスシテド',
  'exercise': 'エクサーシス',
  'expect': 'エクスペクト',
  'expense': 'エクスペンス',
  'expensive': 'エクスペンシブ',
  'experience': 'エクスペリーンス',
  'experiment': 'エクスペリメント',
  'expert': 'エクスパート',
  'explain': 'エクスプレーン',
  'explorer': 'エクスプロラー',
  'export': 'エクスポート',
  'exposure': 'エクスポシュアー',
  'face': 'フェース',
  'facebook': 'フェースブック',
  'fact': 'ファクト',
  'factor': 'ファクター',
  'factory': 'ファクトリ',
  'faculty': 'ファクルティー',
  'fail': 'フェイル',
  'fair': 'フェアー',
  'fall': 'フォール',
  'family': 'ファミリー',
  'famous': 'ファマウス',
  'far': 'ファー',
  'fare': 'フェア',
  'farm': 'ファーム',
  'fast': 'ファースト',
  'fat': 'ファット',
  'fate': 'ファット',
  'father': 'ファーザー',
  'feature': 'フィーチャー',
  'february': 'フェブルアリー',
  'feed': 'フィード',
  'feel': 'フィール',
  'feeling': 'フィーリング',
  'female': 'フェマル',
  'fence': 'フェンス',
  'fern': 'ファーン',
  'fetch': 'フェッチ',
  'field': 'フィールド',
  'fifth': 'フィフス',
  'fifty': 'フィフティー',
  'fight': 'ファイト',
  'fighter': 'ファイター',
  'figure': 'フィギュア',
  'file': 'ファイル',
  'film': 'フィルム',
  'final': 'ファイマル',
  'find': 'フィンド',
  'finding': 'フィンディング',
  'fine': 'ファイン',
  'finger': 'フィンガー',
  'finish': 'フィニッシュ',
  'fire': 'ファイア',
  'firefox': 'ファイヤーフォックス',
  'firm': 'ファーム',
  'firmware': 'ファアーヌウエア',
  'first': 'ファースト',
  'fish': 'フィシュ',
  'fitness': 'フィットネス',
  'five': 'フィブ',
  'flash': 'フラッシュ',
  'flat': 'フラット',
  'flight': 'フライト',
  'floor': 'フルアー',
  'flower': 'フラワー',
  'fly': 'フライ',
  'focus': 'フォーカス',
  'fog': 'フォグ',
  'folder': 'フォルダー',
  'follow': 'フォロー',
  'food': 'フード',
  'foot': 'フィート',
  'football': 'フットボール',
  'for': 'エフオーアール',
  'force': 'フォース',
  'forecast': 'フォーカス',
  'foreign': 'フォライグン',
  'forest': 'フォレスト',
  'forget': 'フォーゲット',
  'form': 'フォーム',
  'formation': 'フォーメーション',
  'formula': 'フォーヌラ',
  'forward': 'フォワード',
  'found': 'ファウンド',
  'four': 'フォー',
  'fourth': 'ファアース',
  'framework': 'フレームワーク',
  'free': 'フリー',
  'fresh': 'フレシュ',
  'freshman': 'フレシュヌン',
  'friday': 'フリデー',
  'friend': 'フレンド',
  'from': 'フロム',
  'front': 'フロント',
  'fruit': 'フルーツ',
  'fujitsu': 'フジトシュ',
  'full': 'フル',
  'fun': 'ファン',
  'function': 'ファンクション',
  'fund': 'ファンド',
  'funeral': 'フヌラル',
  'future': 'ヒューチャー',
  'galaxy': 'ギャラクシー',
  'game': 'ゲーム',
  'garden': 'ガーデン',
  'gas': 'ガス',
  'gate': 'ガット',
  'general': 'ジェナラル',
  'generator': 'ジェネレーター',
  'german': 'ジャーマン',
  'giant': 'ジャイアント',
  'gift': 'ギフト',
  'girl': 'ガール',
  'github': 'ジットハブ',
  'give': 'ギブ',
  'glass': 'ガラス',
  'globalization': 'グローバライゼイション',
  'glue': 'グルー',
  'goal': 'ゴール',
  'goalkeeper': 'ゴールキーパー',
  'gold': 'ゴールド',
  'golf': 'ゴルフ',
  'good': 'グッド',
  'google': 'グーグル',
  'government': 'ゴバーンメント',
  'graduate': 'グラデュアット',
  'grammar': 'グラマー',
  'grand': 'グランデ',
  'grape': 'グレープ',
  'graph': 'グラフ',
  'gray': 'グレー',
  'great': 'グレート',
  'green': 'グリーン',
  'grey': 'グレー',
  'ground': 'グランド',
  'group': 'グループ',
  'grow': 'グロー',
  'growth': 'グロース',
  'guard': 'グアード',
  'guess': 'グス',
  'guest': 'ゲスト',
  'guide': 'ジード',
  'guy': 'ガイ',
  'gym': 'ジム',
  'habit': 'ハビット',
  'hair': 'ヘア',
  'half': 'ハーフ',
  'hall': 'ハル',
  'hamburger': 'ハンバーガー',
  'hand': 'ハンド',
  'happen': 'ハッペン',
  'happy': 'ハッピー',
  'hard': 'ハード',
  'hardware': 'ハード',
  'harm': 'ハーム',
  'hate': 'ハット',
  'have': 'ハブ',
  'head': 'ヘッド',
  'health': 'ヒールス',
  'hear': 'ヒアー',
  'heart': 'ハート',
  'heat': 'ヒート',
  'heavy': 'ヘビー',
  'height': 'ヒーイット',
  'hello': 'ヘロ',
  'help': 'ヘルプ',
  'here': 'ヘアー',
  'hero': 'ヒーロー',
  'high': 'ハイ',
  'hill': 'ヒル',
  'history': 'ヒストリ',
  'hit': 'ヒット',
  'hog': 'ホッグ',
  'hold': 'ホールド',
  'hole': 'ホル',
  'holiday': 'ホリデー',
  'home': 'ホーム',
  'honda': 'ホンダ',
  'hood': 'フード',
  'hope': 'ホープ',
  'horse': 'ホース',
  'hose': 'ホース',
  'hospital': 'ホスピタル',
  'host': 'ホスト',
  'hot': 'ホット',
  'hotel': 'ホテル',
  'hour': 'アワー',
  'house': 'ハウス',
  'how': 'ハウ',
  'huge': 'ヒュッジ',
  'human': 'ヒューマン',
  'hundred': 'ハンドレド',
  'hunt': 'ハント',
  'hurry': 'ヒュリー',
  'hurt': 'ハート',
  'hypothesis': 'ヒポテシス',
  'ice': 'アイス',
  'idea': 'アイディア',
  'illness': 'イルネス',
  'illustration': 'イラストレーション',
  'image': 'イメッジ',
  'impact': 'インパクト',
  'implication': 'インプリケーション',
  'import': 'インポート',
  'improvement': 'イヌプロブヌント',
  'in': 'イン',
  'income': 'インカム',
  'industrial': 'インダストリアル',
  'industry': 'インダストリ',
  'infection': 'インフェクション',
  'inflation': 'インフレ',
  'influence': 'インフルエンス',
  'information': 'インフォメーション',
  'injection': 'インジェクション',
  'injury': 'インジュリー',
  'innovation': 'イノベーション',
  'inside': 'インサイド',
  'institute': 'インスティチュット',
  'instrument': 'インストルメント',
  'insurance': 'インシュアランス',
  'intelligence': 'インテリジェンス',
  'intention': 'インテンション',
  'interest': 'インタレスト',
  'intermediate': 'インターヌディアット',
  'internet': 'インターネット',
  'into': 'イント',
  'intonation': 'イントネーション',
  'investment': 'インベストメント',
  'invoice': 'インボイス',
  'ipad': 'アイパッド',
  'ipcc': 'アイピーシーシー',
  'iphone': 'アイフォン',
  'iron': 'アイロン',
  'island': 'アイランド',
  'jacket': 'ウインドブレーカー',
  'japan': 'ジャパン',
  'jar': 'ジャー',
  'job': 'ジョブ',
  'journalist': 'ジャーナリスト',
  'joy': 'ジョイ',
  'judgment': 'ジャッジメント',
  'juice': 'ジュース',
  'junior': 'ジュニア',
  'just': 'ジャスト',
  'keen': 'キーン',
  'keep': 'キープ',
  'key': 'キー',
  'keyboard': 'カイボアード',
  'kick': 'キック',
  'kid': 'キッド',
  'kill': 'キル',
  'kilt': 'キルト',
  'king': 'キング',
  'kit': 'キット',
  'kitchen': 'キッチン',
  'knew': 'ニュー',
  'knockout': 'ノックアウト',
  'know': 'ノウ',
  'kobe': 'コーベ',
  'kyoto': 'キオト',
  'lake': 'レーク',
  'large': 'ラージ',
  'late': 'ラット',
  'later': 'ラター',
  'lawyer': 'ローイアー',
  'layout': 'レイアウト',
  'leader': 'リーダー',
  'league': 'リーグ',
  'learn': 'リアーン',
  'learning': 'ラーニング',
  'leave': 'リーブ',
  'left': 'レフト',
  'lemon': 'レモン',
  'length': 'レングス',
  'lens': 'レンズ',
  'less': 'レス',
  'letter': 'レター',
  'level': 'レベル',
  'library': 'ライブラリー',
  'license': 'ライセンス',
  'lie': 'ライ',
  'life': 'ライフ',
  'light': 'ライト',
  'like': 'ライク',
  'line': 'ライン',
  'linesman': 'リヌスヌン',
  'link': 'リンク',
  'list': 'リスト',
  'listener': 'リスナー',
  'little': 'リトル',
  'loan': 'ローン',
  'log': 'ログ',
  'login': 'ログイン',
  'long': 'ロング',
  'look': 'ルック',
  'loser': 'ロサー',
  'loss': 'ロス',
  'lot': 'ロット',
  'loud': 'ラウド',
  'love': 'ロブ',
  'lunch': 'ランチ',
  'machine': 'マシーン',
  'macintosh': 'マッキントッシュ',
  'magazine': 'マガジン',
  'mail': 'メール',
  'make': 'メーケ',
  'mall': 'モール',
  'man': 'マン',
  'manager': 'マネージャー',
  'mango': 'マンゴー',
  'manufacture': 'マニュファクチャー',
  'many': 'マニー',
  'map': 'マップ',
  'march': 'マーチ',
  'market': 'マーケット',
  'master': 'マスター',
  'match': 'マッチ',
  'meal': 'ミール',
  'mean': 'メーン',
  'meaning': 'ミーニング',
  'measure': 'メジャー',
  'meat': 'ミート',
  'mechanism': 'メカニズム',
  'medal': 'メダル',
  'medicine': 'メディシン',
  'meet': 'ミート',
  'meeting': 'ミーティング',
  'member': 'メンバー',
  'memory': 'メモリー',
  'mental': 'メンタル',
  'message': 'メッセージ',
  'method': 'メソッド',
  'metro': 'メトロ',
  'middle': 'ミドル',
  'midfielder': 'ヌドフィールダー',
  'might': 'マイト',
  'mile': 'マイル',
  'milk': 'ミルク',
  'millennium': 'ミレニアム',
  'million': 'ミリオン',
  'mind': 'マインド',
  'mine': 'マイン',
  'mineral': 'ミネラル',
  'minute': 'ミニット',
  'mirror': 'ミラー',
  'miso': 'ミソ',
  'mission': 'ヌション',
  'mitsubishi': 'ヌトサビシ',
  'model': 'モデル',
  'modern': 'モダン',
  'money': 'マニー',
  'monkey': 'マンキー',
  'month': 'マンス',
  'mood': 'ムード',
  'moon': 'モーン',
  'more': 'モアー',
  'morning': 'モーニング',
  'mortgage': 'モーゲージ',
  'most': 'モスト',
  'mother': 'マザー',
  'motion': 'モーション',
  'motive': 'モーティブ',
  'motor': 'モーター',
  'mountain': 'マウンテン',
  'mouse': 'マウス',
  'mouth': 'マウス',
  'move': 'モブ',
  'movement': 'ムーブメント',
  'movie': 'ムービー',
  'much': 'マーチョ',
  'multiply': 'マルティプリー',
  'muscle': 'マスクル',
  'museum': 'ミュージアム',
  'music': 'ミュージック',
  'musician': 'ミュージシャン',
  'must': 'マスト',
  'nagoya': 'ナゴヤ',
  'name': 'ネーム',
  'near': 'ニアー',
  'neck': 'ネック',
  'need': 'ニード',
  'nero': 'ネロ',
  'netflix': 'ネットフリックス',
  'network': 'ネットワーク',
  'never': 'ネバー',
  'new': 'ニュー',
  'news': 'ニュース',
  'newspaper': 'ニュースパパー',
  'next': 'ネクスト',
  'night': 'ナイト',
  'nikon': 'ニコン',
  'nine': 'ナン',
  'ninth': 'ヌンス',
  'nissan': 'ヌサン',
  'nmca': 'ンマカ',
  'noise': 'ノイズ',
  'none': 'ノン',
  'noodle': 'ヌードル',
  'noon': 'ノーン',
  'north': 'ノース',
  'not': 'ノット',
  'note': 'ノット',
  'notion': 'ヌション',
  'novel': 'ノブル',
  'now': 'ナウ',
  'nuclear': 'ヌクリアー',
  'number': 'ナンバー',
  'nurse': 'ナース',
  'nutrition': 'ヌトリション',
  'objective': 'オブジェクティブ',
  'ocean': 'オーシャン',
  'of': 'オーエフ',
  'off': 'オフ',
  'offense': 'オフェンス',
  'offer': 'オファー',
  'office': 'オフィス',
  'oil': 'オイル',
  'on': 'オン',
  'once': 'オンス',
  'only': 'オンリー',
  'onto': 'オント',
  'open': 'オペン',
  'operation': 'オペレーション',
  'opinion': 'オピニオン',
  'or': 'オーアール',
  'orange': 'オランジ',
  'order': 'オーダー',
  'organization': 'オーガニゼーション',
  'osaka': 'オーサカ',
  'other': 'オター',
  'out': 'アウト',
  'outside': 'アウトシード',
  'over': 'オバー',
  'owl': 'アウル',
  'packet': 'パケット',
  'page': 'ページ',
  'painter': 'ペーンター',
  'pale': 'パル',
  'panasonic': 'パナソニック',
  'paper': 'ペーパー',
  'park': 'パーク',
  'part': 'パート',
  'partial': 'パーシャル',
  'participant': 'パーティシパント',
  'party': 'パーティー',
  'pass': 'パス',
  'password': 'パスワード',
  'past': 'パスト',
  'pasta': 'パスタ',
  'patient': 'パティーント',
  'pattern': 'パターン',
  'pause': 'ポース',
  'pay': 'ペイ',
  'payment': 'ペイメント',
  'peach': 'ピーチ',
  'pen': 'ペン',
  'pension': 'ペンション',
  'people': 'ピープル',
  'pepper': 'ペッパー',
  'percent': 'パーセント',
  'percentage': 'パーセンテージ',
  'perception': 'パーセプション',
  'person': 'パーソン',
  'ph': 'ペーハー',
  'pharmacist': 'ファーマシスト',
  'pharmacy': 'ファーマシー',
  'phase': 'フェーズ',
  'phone': 'フォン',
  'photo': 'フォト',
  'photographer': 'フォトグラファー',
  'photoshop': 'フォトショップ',
  'physical': 'フィジカル',
  'picture': 'ピクチャー',
  'pill': 'ピル',
  'pineapple': 'パイナップル',
  'pink': 'ピンク',
  'pitch': 'ピッチ',
  'pizza': 'ピザ',
  'place': 'プレイス',
  'plan': 'プラン',
  'plane': 'プレーン',
  'plant': 'プラント',
  'plate': 'プレート',
  'platform': 'プラットフォーム',
  'platinum': 'プラチナ',
  'play': 'プレー',
  'player': 'プレーアー',
  'please': 'プリース',
  'pocket': 'ポケット',
  'poet': 'ポエット',
  'point': 'ポイント',
  'policy': 'ポリシー',
  'pollution': 'ポリューション',
  'pool': 'プール',
  'poor': 'プアー',
  'position': 'ポジション',
  'postgraduate': 'ポストグラデュアット',
  'pot': 'ポット',
  'power': 'パワー',
  'powerpoint': 'パワーポイント',
  'practice': 'プラクティス',
  'prec': 'プレック',
  'present': 'プレセント',
  'president': 'プレジデント',
  'pressure': 'プレッシャー',
  'previous': 'プレビアウス',
  'price': 'プライス',
  'principle': 'プリンシプル',
  'prix': 'プリクス',
  'prize': 'プリズ',
  'problem': 'プロブレム',
  'procedure': 'プロシジャ',
  'process': 'プロセス',
  'production': 'プロダクション',
  'professional': 'プロフェッショナル',
  'professor': 'プロフェッサー',
  'profit': 'プロフィット',
  'program': 'プログラム',
  'programming': 'プログラミング',
  'progress': 'プログレス',
  'project': 'プロジェクト',
  'pronunciation': 'プロヌンシアション',
  'protein': 'プロテイン',
  'psychiatry': 'サイキアトリー',
  'psychological': 'サイコロジカル',
  'psychologist': 'サイコロジスト',
  'pull': 'プル',
  'purple': 'パープル',
  'purpose': 'パーポス',
  'push': 'プッシュ',
  'qualification': 'クアリフィカション',
  'qualifier': 'クアリフィアー',
  'quantity': 'クオンティティー',
  'quarter': 'クアーター',
  'queen': 'クイーン',
  'question': 'クエスチョン',
  'queue': 'クウ',
  'quick': 'クイック',
  'quiet': 'キエット',
  'quilt': 'キルト',
  'quite': 'キット',
  'quote': 'クウォート',
  'radio': 'ラジオ',
  'rain': 'レイン',
  'raise': 'レイズ',
  'rake': 'レーキ',
  'ramen': 'ラーメン',
  'rank': 'ランク',
  'rate': 'レート',
  'read': 'リアド',
  'reader': 'リーダー',
  'real': 'リアル',
  'reason': 'リアソン',
  'receipt': 'レシート',
  'recent': 'リセント',
  'record': 'レコード',
  'recovery': 'リカバリー',
  'recycle': 'リサイクル',
  'referee': 'レフェリー',
  'refuse': 'リフス',
  'reimbursement': 'リーンバーセメント',
  'repeat': 'リピート',
  'researcher': 'リシアーチャー',
  'restaurant': 'レストラン',
  'result': 'リザルト',
  'resume': 'レジヌ',
  'revenue': 'リブヌ',
  'rice': 'ライス',
  'rich': 'リッチ',
  'right': 'ライト',
  'ring': 'リング',
  'risk': 'リスク',
  'river': 'リバー',
  'robot': 'ロボット',
  'rock': 'ロック',
  'rod': 'ロッド',
  'rode': 'ロード',
  'role': 'ロル',
  'room': 'ルーム',
  'round': 'ラウンド',
  'routine': 'ルーチン',
  'rude': 'ルード',
  'rule': 'ルール',
  'run': 'ラン',
  'runner': 'ランナー',
  'safari': 'サファリ',
  'sake': 'サケ',
  'salad': 'サラダ',
  'salary': 'サラリー',
  'sale': 'セール',
  'salt': 'ソルト',
  'same': 'サム',
  'samsung': 'サヌサング',
  'sand': 'サンド',
  'sandwich': 'サンドイッチ',
  'save': 'セーブ',
  'schedule': 'スケジュール',
  'scholar': 'スコラー',
  'school': 'スクール',
  'science': 'サイエンス',
  'scientist': 'サイエンティスト',
  'scope': 'スコープ',
  'score': 'スコア',
  'screen': 'スクリーン',
  'sculptor': 'スクルプター',
  'season': 'シーズン',
  'seat': 'シート',
  'second': 'セコンド',
  'section': 'セクション',
  'seed': 'シード',
  'seek': 'シーク',
  'seem': 'シーム',
  'seen': 'シーン',
  'self': 'セルフ',
  'sell': 'セル',
  'semi': 'セミ',
  'send': 'センド',
  'senior': 'シニア',
  'sense': 'センス',
  'sentence': 'センテンス',
  'sequence': 'シークエンス',
  'server': 'サーバー',
  'set': 'セット',
  'seven': 'セブン',
  'seventh': 'セブンス',
  'shall': 'シャル',
  'shape': 'シェープ',
  'share': 'シェア',
  'shelf': 'シェルフ',
  'shibuya': 'シブヤ',
  'shine': 'シン',
  'ship': 'シップ',
  'shoot': 'シュート',
  'shop': 'ショップ',
  'shopping': 'ショッピッング',
  'short': 'ショート',
  'shot': 'ショット',
  'should': 'シャウルド',
  'shoulder': 'ショルダー',
  'show': 'ショウ',
  'shut': 'シャット',
  'shutter': 'シャッター',
  'side': 'サイド',
  'silver': 'シルバー',
  'since': 'シンス',
  'sing': 'シング',
  'sink': 'シンク',
  'sir': 'サー',
  'site': 'シット',
  'sixth': 'シクスス',
  'size': 'サイズ',
  'skill': 'スキル',
  'skin': 'スキン',
  'sky': 'スカイ',
  'small': 'スモル',
  'snow': 'スノー',
  'soba': 'ソバ',
  'social': 'ソシアル',
  'software': 'ソフトウエア',
  'solar': 'ソーラー',
  'solution': 'ソリューション',
  'some': 'ソム',
  'song': 'ソング',
  'sony': 'ソニー',
  'soon': 'シューン',
  'sophomore': 'ソフォヌアー',
  'sound': 'サウンド',
  'soup': 'スープ',
  'south': 'サウス',
  'space': 'スペース',
  'spare': 'スペア',
  'speak': 'スピーク',
  'specialist': 'スペシャリスト',
  'spectator': 'スペクテーター',
  'speed': 'スピード',
  'spin': 'スピン',
  'spirit': 'スピリット',
  'spot': 'スポット',
  'spring': 'スプリング',
  'spy': 'スパイ',
  'square': 'スクエア',
  'squash': 'スカッシュ',
  'stadium': 'スタジアム',
  'staff': 'スタフ',
  'stage': 'スタッジ',
  'stand': 'スタンド',
  'star': 'スター',
  'start': 'スタート',
  'state': 'ステート',
  'station': 'ステーション',
  'stay': 'ステイ',
  'steel': 'スティール',
  'step': 'ステップ',
  'stew': 'シチュー',
  'still': 'スチール',
  'stock': 'ストック',
  'stomach': 'ストマック',
  'stone': 'ストーン',
  'stood': 'スチュード',
  'stop': 'ストップ',
  'store': 'ストアー',
  'story': 'ストーリー',
  'straight': 'ストレート',
  'strategy': 'ストラテジー',
  'strawberry': 'ストロベリー',
  'street': 'ストリート',
  'strength': 'ストレングス',
  'stress': 'ストレス',
  'stretch': 'ストレッチ',
  'striker': 'ストライカー',
  'strong': 'ストロング',
  'structure': 'ストラクチャー',
  'student': 'スチュデント',
  'study': 'スタディー',
  'subtract': 'サブトラクト',
  'subway': 'サブウェー',
  'such': 'サチ',
  'sugar': 'シュガー',
  'summer': 'サマー',
  'sun': 'サン',
  'supermarket': 'スーパーマーケット',
  'supplement': 'サプリメント',
  'supply': 'サプライ',
  'supporter': 'サポーター',
  'surgeon': 'サーゲオン',
  'sushi': 'サシ',
  'swimmer': 'スイマー',
  'symptom': 'シンプトム',
  'system': 'システム',
  'table': 'タブル',
  'tablet': 'タブレット',
  'tackle': 'タックル',
  'tactic': 'タクティック',
  'take': 'テイク',
  'tale': 'タル',
  'talent': 'タレント',
  'talk': 'タルク',
  'tar': 'ター',
  'task': 'タスク',
  'tax': 'タックス',
  'taxi': 'タクシー',
  'teach': 'ティーチ',
  'teacher': 'ティーチャー',
  'team': 'ティーヌ',
  'technician': 'テクニシャン',
  'technology': 'テクノロジー',
  'television': 'テレビジョン',
  'tell': 'テル',
  'temperature': 'テヌペラチュアー',
  'tempura': 'テンプラ',
  'tenth': 'テンス',
  'teriyaki': 'テリーアキ',
  'term': 'ターム',
  'than': 'タン',
  'thank': 'タンク',
  'that': 'タット',
  'the': 'ザ',
  'their': 'タイア',
  'them': 'テム',
  'then': 'テン',
  'theory': 'セオリー',
  'therapy': 'テラピー',
  'there': 'テアー',
  'these': 'テス',
  'they': 'タイー',
  'thick': 'チック',
  'thin': 'シン',
  'thing': 'チング',
  'think': 'チンク',
  'third': 'サード',
  'this': 'チス',
  'those': 'ソス',
  'thought': 'ソフット',
  'thousand': 'タウサンド',
  'three': 'スリー',
  'threw': 'スリュー',
  'throne': 'スロン',
  'through': 'スロフ',
  'throw': 'スロー',
  'ticket': 'チケット',
  'time': 'タイム',
  'tiny': 'ティニー',
  'tire': 'タイア',
  'to': 'ティーオー',
  'today': 'トデー',
  'together': 'トゥギャザー',
  'toilet': 'トイレ',
  'tokyo': 'トーキョー',
  'tomorrow': 'トヌロー',
  'tone': 'トン',
  'took': 'チューク',
  'tool': 'ツール',
  'toshiba': 'トシバ',
  'total': 'トタル',
  'tote': 'トット',
  'tournament': 'タアーヌヌント',
  'toward': 'タウアード',
  'towel': 'タオル',
  'tower': 'タワー',
  'town': 'タウン',
  'toyo': 'トイオ',
  'toyota': 'トヨタ',
  'track': 'トラック',
  'trade': 'トレード',
  'trading': 'トレーディング',
  'train': 'トレーン',
  'trainer': 'トレーナー',
  'training': 'トレーニング',
  'transfer': 'トランスファー',
  'transformation': 'トランスフォーメーション',
  'transformer': 'トランスフォーマー',
  'travel': 'トラベル',
  'tray': 'トレー',
  'treatment': 'トリートメント',
  'tree': 'ツリー',
  'trillion': 'トリリオン',
  'trip': 'トリップ',
  'trophy': 'トロフィー',
  'true': 'トゥルー',
  'truth': 'トルス',
  'try': 'トライ',
  'tube': 'チュベ',
  'tune': 'タン',
  'turn': 'ターン',
  'tv': 'テレビ',
  'twice': 'トウィス',
  'twitter': 'トゥイッター',
  'udon': 'ウドン',
  'under': 'アンダー',
  'undergraduate': 'アンダーグラデュアット',
  'undo': 'アンドゥ',
  'unit': 'ユニット',
  'university': 'ユニバーシティー',
  'until': 'アンティル',
  'update': 'アップデート',
  'upon': 'ウポン',
  'user': 'ユーザー',
  'vacation': 'バカション',
  'vaccine': 'ワクチン',
  'valley': 'バライー',
  'value': 'バリュー',
  'van': 'バン',
  'variable': 'バリアブル',
  'vegetable': 'ベジタブル',
  'velocity': 'ブロシティー',
  'very': 'ブリー',
  'video': 'ビデオ',
  'view': 'ビュー',
  'viewer': 'ビューアー',
  'village': 'ビレッジ',
  'virus': 'ウイルス',
  'vitamin': 'ビタミン',
  'vocabulary': 'ボキャブラリー',
  'vodka': 'ウォッカ',
  'voice': 'ボイス',
  'voltage': 'ボルテージ',
  'volume': 'ベリューム',
  'vs': 'バーサス',
  'wage': 'ワッジ',
  'wait': 'ウェート',
  'wake': 'ワケ',
  'walk': 'フォアボール',
  'want': 'ワント',
  'war': 'ウォー',
  'warm': 'ウォーム',
  'was': 'ウォズ',
  'wash': 'ワシュ',
  'waste': 'ウェスト',
  'watch': 'ウォッチ',
  'water': 'ワター',
  'wave': 'ワブ',
  'way': 'ウェイ',
  'weakness': 'ウィーヌス',
  'weather': 'ウエザー',
  'web': 'ウェブ',
  'website': 'ウェブシット',
  'wedding': 'ウエディング',
  'week': 'ウィーク',
  'weight': 'ウエート',
  'welcome': 'ウエルカム',
  'well': 'ウェル',
  'went': 'ウェント',
  'were': 'ウェアー',
  'west': 'ウエスト',
  'what': 'ホーット',
  'when': 'ウェン',
  'where': 'ウェアー',
  'which': 'ホイチ',
  'while': 'ホイル',
  'whiskey': 'ウィスキー',
  'white': 'ホワイト',
  'who': 'ダブリュエイチオー',
  'whole': 'ホール',
  'whom': 'ダブリュエイチオーエヌ',
  'whose': 'フース',
  'width': 'ウィドス',
  'wifi': 'ウィフィ',
  'will': 'ウィル',
  'wind': 'ウインド',
  'window': 'ウインドウ',
  'windows': 'ウインドウズ',
  'wine': 'ワイン',
  'winger': 'ウィンガー',
  'winner': 'ウイナー',
  'winter': 'ウィンター',
  'wire': 'ワイヤー',
  'wish': 'ウィシュ',
  'with': 'ウィス',
  'withdrawal': 'ウィスドローアル',
  'wood': 'ウッド',
  'wool': 'ウール',
  'word': 'ワード',
  'work': 'ワーク',
  'worker': 'ワーカー',
  'workout': 'ワーカウット',
  'world': 'ワールド',
  'worthy': 'ワーチー',
  'would': 'ワウルド',
  'write': 'ライト',
  'writer': 'ライター',
  'wrong': 'ロング',
  'yahoo': 'ヤフー',
  'yakisoba': 'ヤキソバ',
  'yakitori': 'ヤキトリ',
  'yard': 'ヤード',
  'year': 'イアー',
  'yellow': 'イエロー',
  'yes': 'イエス',
  'yesterday': 'イエスターデー',
  'yokohama': 'ヨコハマ',
  'york': 'ヨーク',
  'you': 'ユー',
  'young': 'ヤング',
  'your': 'ヤアー',
  'youtube': 'ユーチューブ',
  'zero': 'ゼロ',
  'zip': 'ジップ',
  'zoom': 'ズーム',
  'zoombig': 'ズーヌビグ',
}));

// Evaluate-license mask the SDK DLL applies to its kana output.
// ナ行/マ行 -> ヌ; ン is NOT masked (verified: morning -> ヌーヌング).
const MASKED = new Set('ナニヌネノマミムメモ'.split(''));
export function applyEvalMask(s) {
  let o = '';
  for (const c of s) o += MASKED.has(c) ? 'ヌ' : c;
  return o;
}

const SPELLS_SHORT = 'cot cap sit six to ten red rid row rot hi no'.split(' ');

// --- Syllable-driven fallback engine (ported from analysis/en2kana.js) ---

const SUFFIX = [
  ['izations', 'イゼイションズ'], ['ization', 'イゼイション'], ['ations', 'エーションズ'],
  ['ation', 'エーション'], ['itions', 'イションズ'], ['ition', 'イション'],
  ['tions', 'ションズ'], ['tion', 'ション'],
  ['ments', 'メントス'], ['ment', 'メント'], ['nesses', 'ネスス'], ['ness', 'ネス'],
  ['lessly', 'レスリー'], ['less', 'レス'], ['fully', 'フリー'], ['ful', 'フル'],
  ['ability', 'アビリティー'], ['ibility', 'イビリティー'], ['ible', 'イブル'], ['able', 'エブル'],
  ['ously', 'アスリー'], ['ious', 'アス'], ['ous', 'アス'], ['tely', 'トリー'],
  ['tically', 'ティカリー'], ['ically', 'イカリー'], ['ical', 'イカル'],
  ['logy', 'ロジー'], ['graphy', 'グラフィー'], ['phy', 'フィー'], ['istry', 'イストリー'],
  ['ster', 'スター'], ['ist', 'リスト'], ['ism', 'ズム'],
  ['tively', 'ティブリー'], ['tive', 'ティブ'], ['sive', 'スィブ'], ['ive', 'イブ'],
  ['archy', 'アーキー'], ['cy', 'シー'], ['sy', 'シィ'], ['titude', 'ティチュード'],
  ['itude', 'イチュード'], ['ty', 'ティー'], ['ly', 'リー'], ['ry', 'リー'],
  ['gy', 'ジー'], ['al', 'アル'], ['ian', 'イアン'], ['ion', 'イオン'],
  ['ors', 'アーズ'], ['or', 'オー'], ['ars', 'アーズ'], ['ar', 'アー'],
  ['ery', 'アリー'], ['er', 'アー'], ['ears', 'アーズ'],
].sort((a, b) => b[0].length - a[0].length);

const VTOK = [
  ['eigh', 'エイ'], ['ough', 'フ'], ['eau', 'オー'],
  ['au', 'オー'], ['aw', 'オー'], ['ee', 'イー'], ['oo', 'ウー'], ['oa', 'オー'],
  ['ou', 'アウ'], ['ow', 'アウ'], ['ai', 'エー'], ['ay', 'エー'], ['ei', 'エイ'],
  ['ie', 'イー'], ['ew', 'ユー'], ['oi', 'オイ'], ['oy', 'オイ'], ['igh', 'イ'],
  ['air', 'エア'], ['ear', 'イア'], ['eer', 'イア'], ['our', 'アー'], ['ure', 'アー'],
  ['are', 'アー'], ['ere', 'アー'], ['ore', 'オー'], ['ire', 'アイア'], ['ue', 'ユー'],
  ['ua', 'ウア'], ['ui', 'ウイ'], ['uo', 'ウオ'], ['ae', 'エー'],
  ['ea', 'イー'], ['io', 'イオ'], ['ia', 'イア'], ['eo', 'エオ'],
  ['iu', 'イウ'], ['eu', 'ユー'], ['oe', 'オエ'],
].sort((a, b) => b[0].length - a[0].length);

const CTOK = [
  ['psy', 'サイ'], ['sci', 'サイ'], ['tch', 'ッチ'], ['dge', 'ッジ'], ['nge', 'ンジ'], ['sch', 'シチ'],
  ['sh', 'シュ'], ['ch', 'チ'], ['ck', 'ック'], ['ph', 'フ'], ['th', 'ス'],
  ['gh', ''], ['ng', 'ング'], ['mb', 'ンブ'], ['kn', 'ノ'], ['wr', 'ル'],
  ['wh', 'ウ'], ['qu', 'ク'], ['ps', 'ス'], ['pn', 'ノ'],
  ['ss', 'ス'], ['ll', 'ル'], ['tt', 'ット'], ['dd', 'ッド'], ['bb', 'ブ'],
  ['pp', 'プ'], ['ff', 'フ'], ['rr', 'ル'], ['nn', 'ン'], ['mm', 'ム'],
  ['gg', 'グ'], ['cc', 'ック'],
].sort((a, b) => b[0].length - a[0].length);

const CV = {
  b: { a: 'バ', e: 'ベ', i: 'ビ', o: 'ボ', u: 'ブ' },
  c: { a: 'カ', e: 'セ', i: 'シ', o: 'コ', u: 'ク', y: 'シ' },
  d: { a: 'ダ', e: 'デ', i: 'ディ', o: 'ド', u: 'ドゥ' },
  f: { a: 'ファ', e: 'フェ', i: 'フィ', o: 'フォ', u: 'フ' },
  g: { a: 'ガ', e: 'ジェ', i: 'ギ', o: 'ゴ', u: 'グ', y: 'ジ' },
  h: { a: 'ハ', e: 'ヘ', i: 'ヒ', o: 'ホ', u: 'フ' },
  j: { a: 'ジャ', e: 'ジェ', i: 'ジ', o: 'ジョ', u: 'ジュ' },
  k: { a: 'カ', e: 'ケ', i: 'キ', o: 'コ', u: 'ク' },
  l: { a: 'ラ', e: 'レ', i: 'リ', o: 'ロ', u: 'ル' },
  m: { a: 'マ', e: 'メ', i: 'ミ', o: 'モ', u: 'ム' },
  n: { a: 'ナ', e: 'ネ', i: 'ニ', o: 'ノ', u: 'ヌ' },
  p: { a: 'パ', e: 'ペ', i: 'ピ', o: 'ポ', u: 'プ' },
  q: { a: 'クア', e: 'クエ', i: 'クイ', o: 'クオ', u: 'クウ' },
  r: { a: 'ラ', e: 'レ', i: 'リ', o: 'ロ', u: 'ル' },
  s: { a: 'サ', e: 'セ', i: 'シ', o: 'ソ', u: 'ス', y: 'シ' },
  t: { a: 'タ', e: 'テ', i: 'ティ', o: 'ト', u: 'ツ' },
  v: { a: 'バ', e: 'ベ', i: 'ビ', o: 'ボ', u: 'ブ' },
  w: { a: 'ワ', e: 'ウェ', i: 'ウィ', o: 'ウォ', u: 'ウ' },
  x: { a: 'クサ', e: 'クセ', i: 'クシ', o: 'クソ', u: 'クス' },
  y: { a: 'ヤ', e: 'イェ', i: 'イ', o: 'ヨ', u: 'ユ' },
  z: { a: 'ザ', e: 'ゼ', i: 'ジ', o: 'ゾ', u: 'ズ' },
};
const VOW = 'aeiouy';
const COREV = 'aeiou';

// Word-final consonant clusters map to fixed kana (data-mined, high agreement).
const FINAL_CTOK = [
  ['nt', 'ント'], ['st', 'スト'], ['nd', 'ンド'], ['ng', 'ング'], ['nk', 'ンク'],
  ['rd', 'ード'], ['rt', 'ート'], ['ld', 'ルド'], ['rm', 'ーム'], ['rk', 'ーク'],
  ['sk', 'スク'], ['ct', 'クト'], ['lt', 'ルト'], ['wn', 'ウン'],
].sort((a, b) => b[0].length - a[0].length);
const LONG = { a: 'エー', e: 'イー', i: 'アイ', o: 'オー', u: 'ユー' };
const SHORT = { a: 'ア', e: 'エ', i: 'イ', o: 'オ', u: 'ア' };

export function en2kanaRules(word) {
  const w = word.toLowerCase();
  let out = '';
  let i = 0;
  const n = w.length;
  const isV = (c) => VOW.includes(c);
  const isC = (c) => COREV.includes(c);

  while (i < n) {
    const rest = w.slice(i);

    // short closed C-C-y (dry/fly/sky/spy/try) -> CV[C].a + 'イ' (ドライ)
    if (n === 3 && i === 1 && w[2] === 'y') {
      out += (CV[w[1]] ? CV[w[1]].a : '') + 'イ'; break;
    }

    // 1) suffix
    let suf = null;
    for (const [t, k] of SUFFIX) if (rest === t) { suf = [t, k]; break; }
    if (suf) { out += suf[1]; i += suf[0].length; break; }

    // 2) vowel
    if (isC(w[i])) {
      let v1 = null;
      for (const [t, k] of VTOK) if (rest.startsWith(t)) { v1 = [t, k]; break; }
      if (v1) { out += v1[1]; i += v1[0].length; continue; }
      const ch = w[i];
      // V + r + consonant -> long (arch->アーチ, corner->コーナー, card->カルト excluded
      // as it is a rare short; arr/rr not matched -> アレ/エル handled elsewhere)
      if ((ch === 'a' || ch === 'o' || ch === 'e') && w[i + 1] === 'r' && w[i + 2] !== undefined && !isV(w[i + 2]) && w[i + 2] !== 'r') {
        const lon = { a: 'アー', o: 'オー', e: 'アー' }[ch];
        out += lon; i += 2; continue;
      }
      // CVCe long
      if (i + 1 < n && !isV(w[i + 1]) && i + 2 === n - 1 && w[n - 1] === 'e') {
        out += LONG[ch]; i++; continue;
      }
      // word-final single vowel
      if (i === n - 1) {
        if (ch === 'e') { i++; break; }
        out += ch === 'o' ? 'オ' : ch === 'i' ? 'イ' : ch === 'y' ? 'イ' : ch === 'a' ? 'ア' : 'ウ';
        i++; continue;
      }
      // word-final open(e)
      if (i === n - 2 && w[i + 1] === 'e') { out += LONG[ch]; i += 2; break; }
      // general short read
      out += SHORT[ch]; i++; continue;
    }

    // 3) y
    if (w[i] === 'y') { out += 'イ'; i++; continue; }

    // word-final C+y -> CV[C].i + ー (party->パーティー, body->ボディー, copy->コピー)
    // except short closed C-C-y (dry/fly/sky/spy/try) -> CV[C].a + 'イ' (ドライ)
    if (i === n - 2 && w[i + 1] === 'y') {
      const ci = CV[w[i]] ? CV[w[i]].i : '';
      if (n === 3) { out += (CV[w[i]] ? CV[w[i]].a : '') + 'イ'; i += 2; continue; }
      out += ci + 'ー'; i += 2; continue;
    }

    // suffix must also win here: a trailing -tion etc can begin mid-word with a
    // consonant (plication->プリケーション) because section 4/5 would eat the 't'.
    {
      let suf2 = null;
      for (const [t, k] of SUFFIX) if (rest === t) { suf2 = [t, k]; break; }
      if (suf2) { out += suf2[1]; i += suf2[0].length; break; }
    }

    // 4) consonant cluster + following vowel cluster
    {
      let cc = null;
      for (const [t, k] of CTOK) if (rest.startsWith(t)) { cc = [t, k]; break; }
      if (cc) {
        const cl = cc[0].length;
        const sub = w.slice(i + cl);
        // -nger/-ngar: nasal n + g{er|ar} (danger->ダンガー, finger->フィンガー)
        if (cc[0] === 'nge' && (sub === 'r' || sub === 'ar')) {
          out += 'ン'; i += 1; continue;
        }
        if (sub && isC(sub[0])) {
          let v1 = null;
          for (const [t, k] of VTOK) if (sub.startsWith(t)) { v1 = [t, k]; break; }
          if (v1) {
            if (sub.startsWith('ea') && !sub.startsWith('ear')) { out += cc[1]; i += cl + 2; continue; }
            out += cc[1]; i += cl + v1[0].length; continue;
          }
          out += cc[1]; i += cl; continue;
        } else {
          out += cc[1]; i += cl; continue;
        }
      }
    }

    // 5) single consonant + vowel(cluster)
    {
      const nx = i + 1 < n ? w[i + 1] : '#';
      if (isC(nx)) {
        // word-final C{er|or|ar} (danger->ダンガー, doctor->ドクター, car->カー)
        if (i + 2 === n - 1 && (w[i + 1] === 'e' || w[i + 1] === 'o' || w[i + 1] === 'a') && w[i + 2] === 'r') {
          let ck = CV[w[i]] ? CV[w[i]].a : '';
          if (ck.length > 0 && ck.slice(-1) === 'ア') ck = ck.slice(0, -1);
          out += ck + 'ー';
          i += 3;
          continue;
        }
        const sub = w.slice(i + 1);
        let v1 = null;
        for (const [t, k] of VTOK) if (sub.startsWith(t)) { v1 = [t, k]; break; }
        if (v1) {
          let ck = CV[w[i]] ? CV[w[i]][sub[0]] : '';
          // ea: C+ea -> C+イー (beach->ビーチ); C+ear -> C+イア (bear->ビアー)
          if (sub.startsWith('ea')) {
            const ci = CV[w[i]] ? CV[w[i]].i : '';
            if (sub.startsWith('ear')) { out += ci + 'アー'; i += 1 + 3; continue; }
            out += ci + 'ー'; i += 1 + 2; continue;
          }
          // ee: C+ee -> C+イー (keep->キープ, deep->ディープ)
          if (sub.startsWith('ee')) {
            const ci = CV[w[i]] ? CV[w[i]].i : '';
            out += ci + 'ー'; i += 1 + 2; continue;
          }
          // ia/io: C+ia -> C+イア (media->メディア, bacteria->バクテリア);
          // C+io -> C+イオ (radio->ラジオ)
          if (sub.startsWith('ia')) { out += (CV[w[i]] ? CV[w[i]].i : '') + 'ア'; i += 1 + 2; continue; }
          if (sub.startsWith('io')) { out += (CV[w[i]] ? CV[w[i]].i : '') + 'オ'; i += 1 + 2; continue; }
          // oo: C+oo -> C+ウー (cool->クール, food->フード, pool->プール);
          // short oo before doubled k/d/t/f (book/cook/look/good/foot) -> C+ウ + 促音
          if (sub.startsWith('oo')) {
            const cu = CV[w[i]] ? CV[w[i]].u : '';
            const a2 = sub[2], a3 = sub[3];
            if ((a2 === 'k' && a3 === 'k') || (a2 === 'd' && a3 === 'd') || (a2 === 't' && a3 === 't')) {
              out += cu + 'ッ';
              i += 1 + 2;
              continue;
            }
            if (a2 === 'k' && a3 === undefined) { out += cu + 'ッ'; i += 1 + 2; continue; }
            if (a2 === 'd' && a3 === undefined) { out += cu + 'ッ'; i += 1 + 2; continue; }
            if (a2 === 't' && i + 3 === n - 1) { // foot/football-ish word-final -oot
              out += cu + 'ッ';
              i += 1 + 2;
              continue;
            }
            out += cu + 'ー'; i += 1 + 2; continue;
          }
          out += ck + v1[1];
          i += 1 + v1[0].length;
          continue;
        }
        // nce/nce-final: c+e after n -> ス (dance->ダンス, fence->フェンス, since->シンス)
        if (w[i] === 'c' && nx === 'e' && w[i - 1] === 'n') {
          out += 'ス'; i += 2; continue;
        }
        // C + V + r + C -> long (corner->コーナー, garden->ガーデン, force->フォース)
        // rare short exceptions: card, modern, certificate
        if (w[i + 2] === 'r' && w[i + 3] !== undefined && !isV(w[i + 3]) && w[i + 3] !== 'r') {
          const ex = w.slice(i, i + 4);
          if (ex !== 'card' && ex !== 'dern' && ex !== 'cert') {
            const segv = CV[w[i]] ? CV[w[i]][nx] : '';
            out += segv + 'ー'; i += 3; continue;
          }
        }
        let seg = CV[w[i]] ? CV[w[i]][nx] : '';
        out += seg; i += 2; continue;
      }
    }

    // 5.5) word-final consonant cluster (nt/st/nd/ng/nk/rd/rt/ld/rm/sk/ct/lt/wn...)
    // must be matched whole, otherwise the tail is consumed letter-by-letter wrongly.
    {
      let f = null;
      for (const [t, k] of FINAL_CTOK) if (rest === t) { f = [t, k]; break; }
      if (f) {
        // card is the rare short exception (card->カルト); all other -ard -> ード
        if (f[0] === 'rd' && rest === 'rd' && w === 'card') {
          out += 'ルト';
          i += 2;
          break;
        }
        out += f[1];
        i += f[0].length;
        break;
      }
    }

    // 6) word-final / single consonant
    const c = w[i];
    let end = '';
    if (c === 'n') end = 'ン';
    else if (c === 'm') end = 'ム';
    else if (c === 's') end = 'ス';
    else if (c === 'd') end = 'ド';
    else if (c === 't') end = 'ト';
    else if (c === 'r') end = 'ル';
    else if (c === 'l') end = 'ル';
    else if (c === 'k') end = '';
    else if (c === 'g') end = 'グ';
    else if (c === 'f') end = 'フ';
    else if (c === 'p') end = 'プ';
    else if (c === 'b') end = 'ブ';
    else if (c === 'x') end = 'クス';
    else if (c === 'z') end = 'ズ';
    else if (c === 'v') end = 'ブ';
    else if (c === 'h') end = '';
    else if (c === 'w') end = 'ウ';
    else if (c === 'c') end = 'ク';
    // Sokuon: word-final t/p/k (or c) after a short vowel in a CVC or VV(short)
    // tail -> geminate (cat->キャット, drop->ドロップ, book->ブック, about->アバウット).
    // Avoid long-vowel digraphs (ea/ee/oo/oa/sou/ai/ay) -> beat/keep/foot/soup stay long.
    if (i === n - 1 && (c === 't' || c === 'p' || c === 'k' || c === 'c')) {
      const pv = w[i - 1];
      const prev = w[i - 2];
      const isShortDigraph = (pv === 'o' && prev === 'u') || (pv === 'w' && prev === 'o'); // ou/ow
      if (COREV.includes(pv) && (isShortDigraph || (prev !== undefined && !VOW.includes(prev)))) {
        if (!(pv === 'e' && w[i - 3] === 'e') && !(pv === 'e' && w[i - 3] === 'a')) {
          end = 'ッ' + end;
        }
      }
    }
    // word-final k after ee/ea/oo keeps ク (week->ウィーク, seek->シーク) but
    // short-vowel k was already geminated above or silent elsewhere (dark->ダーク).
    if (c === 'k' && i === n - 1) {
      const pv = w[i - 1];
      const prev = w[i - 2];
      if ((pv === 'e' && prev === 'e') || (pv === 'e' && prev === 'a') || (pv === 'o' && prev === 'o')) {
        end = 'ク';
      }
    }
    out += end; i++;
  }
  return out;
}

export function englishToKana(word) {
  const lower = word.toLowerCase();
  if (WORD_TABLE.has(lower)) return WORD_TABLE.get(lower);
  const clean = word.replace(/[^A-Za-z]/g, '');
  if (clean.length === 0) return null;
  if (clean.length === 1) return LETTER_NAME[clean.toUpperCase()] ?? null;
  if (clean.length <= 3) {
    if (SPELLS_SHORT.includes(clean)) return [...clean].map((c) => LETTER_NAME[c.toUpperCase()]).join('');
    if (WORD_TABLE.has(clean)) return WORD_TABLE.get(clean);
    return [...clean].map((c) => LETTER_NAME[c.toUpperCase()]).join('');
  }
  return en2kanaRules(clean);
}
