// Standard Japanese loansheet readings (unmasked) for common English words.
// These fill the n/m row of words the eval DLL masked to ヌ. The DLL structure
// is preserved elsewhere; only the masked char is filled from these.
// (Verb-load: these are the conventional katakana loanwords.)
export const STANDARD_LOAN = {
  afternoon: 'アフタヌーン', algorithm: 'アルゴリズム', amount: 'アマウント',
  analysis: 'アナリシス', analyst: 'アナリスト', anniversary: 'アニバーサリー',
  appointment: 'アポイントメント', aquarium: 'アクアリウム', arena: 'アリーナ',
  arm: 'アーム', arrangement: 'アレンジメント', assumption: 'アサンプション',
  automation: 'オートメーション', autumn: 'オータム', banana: 'バナナ',
  bathroom: 'バスルーム', bedroom: 'ベッドルーム', beginner: 'ビギナー',
  beginning: 'ビギニング', benefit: 'ベネフィット', camera: 'カメラ',
  canon: 'キャノン', championship: 'チャンピオンシップ', channel: 'チャネル',
  christmas: 'クリスマス', cinch: 'シンチ', chrome: 'クローム',
  claim: 'クレーム', climate: 'クライメット', clinic: 'クリニック',
  cognitive: 'コグニティブ', come: 'カム', command: 'コマンド',
  commerce: 'コマース', company: 'カンパニー', compass: 'コンパス',
  competition: 'コンペティション', complete: 'コンプリート',
  composition: 'コンポジション', computing: 'コンピューティング',
  consumer: 'コンシューマー', continent: 'コンティネント',
  continue: 'コンティニュー', convenience: 'コンビニエンス',
  corner: 'コーナー', customer: 'カスタマー', department: 'デパートメント',
  designer: 'デザイナー', development: 'デベロップメント',
  diagnosis: 'ダイアグノーシス', diagram: 'ダイアグラム', diploma: 'ディプロマ',
  economist: 'エコノミスト', economy: 'エコノミー', elementary: 'エレメンタリー',
  emotional: 'エモーショナル', enormous: 'エノーマス', equipment: 'イクイップメント',
  estimate: 'エスティメット', evening: 'イブニング', experiment: 'エクスペリメント',
  film: 'フィルム', finish: 'フィニッシュ', firmware: 'ファームウェア',
  fitness: 'フィットネス', formation: 'フォーメーション', formula: 'フォーミュラ',
  framework: 'フレームワーク', freshman: 'フレッシュマン', funeral: 'フューネラル',
  generator: 'ジェネレーター', grammar: 'グラマー', gym: 'ジム',
  illness: 'イルネス', image: 'イメージ', improvement: 'インプルーブメント',
  income: 'インカム', information: 'インフォメーション', innovation: 'イノベーション',
  instrument: 'インストルメント', internet: 'インターネット',
  intonation: 'イントネーション', investment: 'インベストメント',
  journalist: 'ジャーナリスト', judgment: 'ジャッジメント', junior: 'ジュニア',
  knockout: 'ノックアウト', know: 'ノウ', learning: 'ラーニング',
  lemon: 'レモン', linesman: 'ラインズマン', listener: 'リスナー',
  macintosh: 'マッキントッシュ', magazine: 'マガジン', mail: 'メール',
  mall: 'モール', manager: 'マネージャー', mango: 'マンゴー',
  manufacture: 'マニュファクチャー', map: 'マップ', master: 'マスター',
  meal: 'ミール', meaning: 'ミーニング', measure: 'メジャー', meat: 'ミート',
  mechanism: 'メカニズム', medal: 'メダル', medicine: 'メディシン',
  meeting: 'ミーティング', member: 'メンバー', memory: 'メモリー',
  mental: 'メンタル', message: 'メッセージ', method: 'メソッド', metro: 'メトロ',
  middle: 'ミドル', midfielder: 'ミッドフィールダー', milk: 'ミルク',
  millennium: 'ミレニアム', million: 'ミリオン', mineral: 'ミネラル',
  minute: 'ミニット', miso: 'ミソ', mission: 'ミッション', mitsubishi: 'ミツビシ',
  model: 'モデル', modern: 'モダン', mood: 'ムード', mortgage: 'モーゲージ',
  motion: 'モーション', motive: 'モーティブ', motor: 'モーター',
  mountain: 'マウンテン', movement: 'ムーブメント', multiply: 'マルティプライ',
  muscle: 'マッスル', museum: 'ミュージアム', neck: 'ネック', network: 'ネットワーク',
  next: 'ネクスト', nikon: 'ニコン', ninth: 'ナインス', nissan: 'ニッサン',
  noodle: 'ヌードル', notion: 'ノーション', novel: 'ノベル', nuclear: 'ニュークリア',
  nurse: 'ナース', nutrition: 'ニュートリション', opinion: 'オピニオン',
  organization: 'オーガニゼーション', panasonic: 'パナソニック', payment: 'ペイメント',
  pharmacist: 'ファーマシスト', pharmacy: 'ファーマシー', pineapple: 'パイナップル',
  platform: 'プラットフォーム', platinum: 'プラチナ', professional: 'プロフェッショナル',
  programming: 'プログラミング', pronunciation: 'プロナンシエーション',
  ramen: 'ラーメン', reimbursement: 'リインバースメント', resume: 'レジュメ',
  revenue: 'レベニュー', runner: 'ランナー', samsung: 'サムソン', semi: 'セミ',
  senior: 'シニア', snow: 'スノー', some: 'サム', sony: 'ソニー',
  sophomore: 'ソフォモア', stadium: 'スタジアム', stomach: 'ストマック',
  summer: 'サマー', supermarket: 'スーパーマーケット', supplement: 'サプリメント',
  swimmer: 'スイマー', symptom: 'シンプトム', team: 'チーム',
  technician: 'テクニシャン', technology: 'テクノロジー', temperature: 'テンペラチュア',
  tempura: 'テンプラ', tiny: 'タイニー', tomorrow: 'トゥモロー',
  tournament: 'トーナメント', trainer: 'トレーナー', training: 'トレーニング',
  transformation: 'トランスフォーメーション', transformer: 'トランスフォーマー',
  treatment: 'トリートメント', unit: 'ユニット', university: 'ユニバーシティー',
  vitamin: 'ビタミン', volume: 'ボリューム', weakness: 'ウィークネス',
  winner: 'ウィナー',
};

export function standardLoan(word) {
  return STANDARD_LOAN[word.toLowerCase()];
}